(define (verify-uil program) program)
(define (verify-scheme program) program)

(load "src/utils.scm")
(load "src/lift-letrec.scm")
(load "src/normalize-context.scm")
(load "src/specify-representation.scm")
(load "src/uncover-locals.scm")
(load "src/remove-let.scm")
(load "src/remove-complex-opera*.scm")
(load "src/flatten-set!.scm")
(load "src/impose-calling-conventions.scm")
(load "src/expose-allocation-pointer.scm")
(load "src/pre-assign-frame.scm")
(load "src/assign-new-frame.scm")
(load "src/finalize-frame-locations.scm")
(load "src/select-instructions.scm")
(load "src/uncover-frame-conflict.scm")
(load "src/uncover-register-conflict.scm")
(load "src/assign-registers.scm")
(load "src/assign-frame.scm")
(load "src/discard-call-live.scm")
(load "src/finalize-locations.scm")
(load "src/expose-frame-var.scm")
(load "src/expose-memory-operands.scm")
(load "src/expose-basic-blocks.scm")
(load "src/optimize-jumps.scm")
(load "src/flatten-program.scm")
(load "src/generate-x86-64.scm")
